const piclist = [
  {
    id: 25433188626,
    name: "网红冰丝防晒纹身袖套夏季防紫外线男女花臂胳膊开车手套护臂国潮1条J12",
    sellCount: 0,
    likeCount: 0,
    sellStatus: 0,
    picture:
      "http://p1.meituan.net/shangouproductapi/8ee371a32402851238450cbdc91b121c181363.jpg@88h_88w_1e",
    tagId: 1194052965,
    tagName: "防晒必备",
    wmProductSkus: [
      {
        id: 47431292372,
        spec: "牡丹+一只装",
        price: 19.9,
        discountPrice: -1,
        stock: 999,
        boxPrice: 0,
        boxNum: 1,
        upcCode: "",
        sourceFoodCode: "",
        weight: 99,
        weight_unit: "克(g)",
        minOrderCount: 1,
        weight4g: 0,
        sellStatus: 0,
      },
      {
        id: 47431292373,
        spec: "青龙+一只装",
        price: 19.9,
        discountPrice: -1,
        stock: 999,
        boxPrice: 0,
        boxNum: 1,
        upcCode: "",
        sourceFoodCode: "",
        weight: 99,
        weight_unit: "克(g)",
        minOrderCount: 1,
        weight4g: 0,
        sellStatus: 0,
      },
      {
        id: 47431292374,
        spec: "善恶+一只装",
        price: 19.9,
        discountPrice: -1,
        stock: 999,
        boxPrice: 0,
        boxNum: 1,
        upcCode: "",
        sourceFoodCode: "",
        weight: 99,
        weight_unit: "克(g)",
        minOrderCount: 1,
        weight4g: 0,
        sellStatus: 0,
      },
      {
        id: 47431292375,
        spec: "般若+一只装",
        price: 19.9,
        discountPrice: -1,
        stock: 999,
        boxPrice: 0,
        boxNum: 1,
        upcCode: "",
        sourceFoodCode: "",
        weight: 99,
        weight_unit: "克(g)",
        minOrderCount: 1,
        weight4g: 0,
        sellStatus: 0,
      },
    ],
    categoryId: 200005637,
    categoryName: "其他配饰",
    brandId: 0,
    spBrandId: 0,
    brandSourceType: 0,
    brandName: null,
    incomplete: 0,
    fillOrCheck: 0,
    isSp: 0,
    spId: null,
    upcCode: "",
    description: "",
    attrList: [],
    wmProductSpuExtends: null,
    unreleasedId: 0,
    suggestCategoryId: 0,
    isStopSell: 0,
    isPlatformStopSell: 0,
    unComplianceFlag: 0,
    originName: null,
    nameClone: null,
    flavour: null,
    tagCount: 1,
    smartSort: null,
    pictures: [
      "http://p1.meituan.net/shangouproductapi/8ee371a32402851238450cbdc91b121c181363.jpg",
      "http://p1.meituan.net/shangouproductapi/19ed8ee9db8a36c446a08e48fed1d052247546.jpg",
      "http://p0.meituan.net/shangouproductapi/a2e43a01bc4af93b551b66273ee40539226149.jpg",
      "http://p0.meituan.net/shangouproductapi/94a20ef6891bdcd9f84c8e7ee5756c23236383.jpg",
      "http://p0.meituan.net/shangouproductapi/10d4a759c5b8d662d9ba4f6ff3016e7c267927.jpg",
      "",
      "",
      "",
      "",
      "",
    ],
    approvalNumberPics: null,
    isSupportApprovalNumberPic: 0,
    labels: null,
    wmProductVideo: null,
    platformLimitSaleRule: null,
    tagList: [
      {
        id: 1194052965,
        wm_poi_id: 0,
        poi_id: 0,
        name: "防晒必备",
        sequence: 0,
        ctime: 0,
        utime: 0,
        valid: 1,
        description: "",
        act_policy_id: 0,
        wm_category_code: "",
        node_path: "",
        level: 2,
        parent_id: 1199067084,
        buz_type: 0,
        app_tag_code: "",
        top_flag: 0,
        time_zone: "",
        tag_type: 0,
        is_leaf: 1,
        outer_ftag_id: -1,
        extend: '{"sortType":0,"status":0,"topCount":0}',
        children: null,
        tempTagId: 0,
        hqTagId: 0,
        hqId: 0,
        is_top: 0,
        tagrelSequence: 0,
        marketplaceId: null,
        overrideConfig: 0,
        cStatus: 0,
        templateId: 0,
        markIds: null,
        setDescription: true,
        setExtend: true,
        setHqId: false,
        setMarketplaceId: false,
        setOverrideConfig: false,
        setPoi_id: false,
        setTag_type: false,
        setSequence: false,
        setValid: false,
        setCtime: false,
        setUtime: false,
        setId: true,
        setName: true,
        setLevel: true,
        setWm_category_code: true,
        setWm_poi_id: false,
        setIs_top: false,
        setTemplateId: false,
        setAct_policy_id: false,
        setNode_path: true,
        setParent_id: true,
        setBuz_type: false,
        setApp_tag_code: true,
        setTop_flag: true,
        setTime_zone: true,
        setIs_leaf: true,
        setOuter_ftag_id: false,
        childrenSize: 0,
        childrenIterator: null,
        setChildren: false,
        setTempTagId: false,
        setHqTagId: false,
        setTagrelSequence: true,
        cstatus: 0,
        setCStatus: false,
        markIdsSize: 0,
        markIdsIterator: null,
        setMarkIds: false,
      },
    ],
    categoryNamePath: "服饰鞋包,服饰配饰,其他配饰",
    categoryIdPath: ",200001071,200001080,200005637,",
    auditStatus: 2,
    complianceStatus: 2,
    compositeAuditStatus: 2,
    categoryType: 0,
    missingRequiredInfo: false,
    auditCreateTime: 0,
    auditUpdateTime: 0,
    saveOrUpdate: 0,
    auditUpdateData: false,
    sgLabels: null,
    combinationLabel: 2,
    skuId: 0,
    saleType: 1,
    shippingTime: '{"code":1,"value":"-"}',
    gracePeriodEndTime: 0,
    approachSoldOut: false,
    recommandAvailableTime: null,
    violationId: null,
    platformStopSellLabelMsg: null,
    platformStopSellTips: null,
    cspuId: 0,
    cspuIdMergedSpuCount: 0,
    cpvGuidePicList: [],
    cpvGuidePicConfigList: [],
    appSpuCode: "mtcode_2044738596410064902",
    enableStockEditing: true,
    combineSubSpu: false,
    noStockAutoClear: false,
    limitRuleId: 0,
  },
  {
    id: 25266384479,
    name: "静音户外运动男生凉拖鞋踩屎感街头耐磨防滑男士夏季爆款增高软底 XZ74",
    sellCount: 0,
    likeCount: 0,
    sellStatus: 0,
    picture:
      "http://p0.meituan.net/shangouproductapi/0b4f1d5ecc453d07c18229c0668ad48b437186.jpg@88h_88w_1e",
    tagId: 1194074432,
    tagName: "拖鞋凉鞋",
    wmProductSkus: [
      {
        id: 47185644500,
        spec: "白色+40-41",
        price: 59,
        discountPrice: -1,
        stock: 999,
        boxPrice: 0,
        boxNum: 1,
        upcCode: "",
        sourceFoodCode: "",
        weight: 99,
        weight_unit: "克(g)",
        minOrderCount: 1,
        weight4g: 0,
        sellStatus: 0,
      },
      {
        id: 47185644501,
        spec: "白色+42-43",
        price: 59,
        discountPrice: -1,
        stock: 999,
        boxPrice: 0,
        boxNum: 1,
        upcCode: "",
        sourceFoodCode: "",
        weight: 99,
        weight_unit: "克(g)",
        minOrderCount: 1,
        weight4g: 0,
        sellStatus: 0,
      },
      {
        id: 47185644502,
        spec: "白色+44-45",
        price: 59,
        discountPrice: -1,
        stock: 999,
        boxPrice: 0,
        boxNum: 1,
        upcCode: "",
        sourceFoodCode: "",
        weight: 99,
        weight_unit: "克(g)",
        minOrderCount: 1,
        weight4g: 0,
        sellStatus: 0,
      },
    ],
    categoryId: 200001086,
    categoryName: "男士拖鞋",
    brandId: 0,
    spBrandId: 0,
    brandSourceType: 0,
    brandName: null,
    incomplete: 0,
    fillOrCheck: 0,
    isSp: 0,
    spId: null,
    upcCode: "",
    description: "",
    attrList: [],
    wmProductSpuExtends: null,
    unreleasedId: 0,
    suggestCategoryId: 0,
    isStopSell: 0,
    isPlatformStopSell: 0,
    unComplianceFlag: 0,
    originName: null,
    nameClone: null,
    flavour: null,
    tagCount: 1,
    smartSort: null,
    pictures: [
      "http://p0.meituan.net/shangouproductapi/0b4f1d5ecc453d07c18229c0668ad48b437186.jpg",
      "http://p0.meituan.net/shangouproductapi/a0811122d7de6728f4a544a78dc29bc8261485.jpg",
      "http://p0.meituan.net/shangouproductapi/550db9f4edd380417e7ffd4cf806e291206925.jpg",
      "http://p0.meituan.net/shangouproductapi/120091ea1b8cf2c1f837ce129f949295321193.jpg",
      "http://p0.meituan.net/shangouproductapi/e1029878e03b38cae778640a9ceeed43328293.jpg",
      "http://p0.meituan.net/shangouproductapi/1553df62326ce2a2431a0b314d519f97497357.jpg",
      "http://p0.meituan.net/shangouproductapi/3213c59fbe18553508eebb0e13d63f08663717.jpg",
      "http://p1.meituan.net/shangouproductapi/173683cd8eefa9a90f97c65dd440eb0d511874.jpg",
      "http://p0.meituan.net/shangouproductapi/89c78229271f1003deeff3011b9ca74e586846.jpg",
      "http://p0.meituan.net/shangouproductapi/3fbeb04eca1f77abb2f6510998de1d3d450140.jpg",
    ],
    approvalNumberPics: null,
    isSupportApprovalNumberPic: 0,
    labels: null,
    wmProductVideo: null,
    platformLimitSaleRule: null,
    tagList: [
      {
        id: 1194074432,
        wm_poi_id: 0,
        poi_id: 0,
        name: "拖鞋凉鞋",
        sequence: 0,
        ctime: 0,
        utime: 0,
        valid: 1,
        description: "",
        act_policy_id: 0,
        wm_category_code: "",
        node_path: "",
        level: 2,
        parent_id: 1194063567,
        buz_type: 0,
        app_tag_code: "",
        top_flag: 0,
        time_zone: "",
        tag_type: 0,
        is_leaf: 1,
        outer_ftag_id: -1,
        extend: '{"sortType":0,"status":0,"topCount":0}',
        children: null,
        tempTagId: 0,
        hqTagId: 0,
        hqId: 0,
        is_top: 0,
        tagrelSequence: 0,
        marketplaceId: null,
        overrideConfig: 0,
        cStatus: 0,
        templateId: 0,
        markIds: null,
        setDescription: true,
        setExtend: true,
        setHqId: false,
        setMarketplaceId: false,
        setOverrideConfig: false,
        setPoi_id: false,
        setTag_type: false,
        setSequence: false,
        setValid: false,
        setCtime: false,
        setUtime: false,
        setId: true,
        setName: true,
        setLevel: true,
        setWm_category_code: true,
        setWm_poi_id: false,
        setIs_top: false,
        setTemplateId: false,
        setAct_policy_id: false,
        setNode_path: true,
        setParent_id: true,
        setBuz_type: false,
        setApp_tag_code: true,
        setTop_flag: true,
        setTime_zone: true,
        setIs_leaf: true,
        setOuter_ftag_id: false,
        childrenSize: 0,
        childrenIterator: null,
        setChildren: false,
        setTempTagId: false,
        setHqTagId: false,
        setTagrelSequence: true,
        cstatus: 0,
        setCStatus: false,
        markIdsSize: 0,
        markIdsIterator: null,
        setMarkIds: false,
      },
    ],
    categoryNamePath: "服饰鞋包,男鞋,男士拖鞋",
    categoryIdPath: ",200001071,200001074,200001086,",
    auditStatus: 2,
    complianceStatus: 2,
    compositeAuditStatus: 2,
    categoryType: 0,
    missingRequiredInfo: false,
    auditCreateTime: 0,
    auditUpdateTime: 0,
    saveOrUpdate: 0,
    auditUpdateData: false,
    sgLabels: null,
    combinationLabel: 2,
    skuId: 0,
    saleType: 1,
    shippingTime: '{"code":1,"value":"-"}',
    gracePeriodEndTime: 0,
    approachSoldOut: false,
    recommandAvailableTime: null,
    violationId: null,
    platformStopSellLabelMsg: null,
    platformStopSellTips: null,
    cspuId: 0,
    cspuIdMergedSpuCount: 0,
    cpvGuidePicList: [],
    cpvGuidePicConfigList: [
      {
        imgTitle: "吊牌及洗唛",
        imgDesc:
          "建议优先上线吊牌及洗唛，同时支持单商品上传多张图片，信息在不同图片时需包含【执行标准号】、【安全类别】、【面料成分含量】、【面料成分】，图片中的有效文本内容要清晰、可识别，无模糊、反光、过曝和有水印等问题。图片和文字需正向，背景无杂乱，裁切、遮挡、折叠、阴影等。",
        imgType: 7,
        urlList: [
          "https://p0.meituan.net/sgspyy/a8ad3b6fb91180134ae4182cf94a13be15105.jpg",
          "https://p0.meituan.net/sgspyy/ae4e35870daa0b98ac9aa5663b2f725018045.jpg",
          "https://p0.meituan.net/sgspyy/dc47af058e3bc81ccd43aacb201de4a723290.jpg",
          "https://p1.meituan.net/sgspyy/6587afcb6d910cbc130eed31bcda270f38717.jpg",
        ],
        picNumLimit: 4,
        picRequired: false,
        picPriority: 3,
        customerDisplayUrl:
          "https://p1.meituan.net/sgspyy/944f6e6f5e27fa47d1ed3d6a1bb55d6057708.jpg",
        cDisplay: 1,
      },
    ],
    appSpuCode: "mtcode_2041439935219134552",
    enableStockEditing: true,
    combineSubSpu: false,
    noStockAutoClear: false,
    limitRuleId: 0,
  },
  {
    id: 25266896169,
    name: "烟灰男士洞洞鞋软底防滑夏季户外运动厚底凉拖鞋镂空轻便时尚潮流青年XZ73",
    sellCount: 0,
    likeCount: 0,
    sellStatus: 0,
    picture:
      "http://p1.meituan.net/shangouproductapi/b783a8f3a5cab13f6f98747ee01eb574347031.jpg@88h_88w_1e",
    tagId: 1194074432,
    tagName: "拖鞋凉鞋",
    wmProductSkus: [
      {
        id: 47180512089,
        spec: "款式一+40-41",
        price: 59,
        discountPrice: -1,
        stock: 999,
        boxPrice: 0,
        boxNum: 1,
        upcCode: "",
        sourceFoodCode: "",
        weight: 99,
        weight_unit: "克(g)",
        minOrderCount: 1,
        weight4g: 0,
        sellStatus: 0,
      },
      {
        id: 47180512090,
        spec: "款式一+42-43",
        price: 59,
        discountPrice: -1,
        stock: 999,
        boxPrice: 0,
        boxNum: 1,
        upcCode: "",
        sourceFoodCode: "",
        weight: 99,
        weight_unit: "克(g)",
        minOrderCount: 1,
        weight4g: 0,
        sellStatus: 0,
      },
      {
        id: 47180512091,
        spec: "款式一+44-45",
        price: 59,
        discountPrice: -1,
        stock: 999,
        boxPrice: 0,
        boxNum: 1,
        upcCode: "",
        sourceFoodCode: "",
        weight: 99,
        weight_unit: "克(g)",
        minOrderCount: 1,
        weight4g: 0,
        sellStatus: 0,
      },
    ],
    categoryId: 200001085,
    categoryName: "男士凉鞋",
    brandId: 0,
    spBrandId: 0,
    brandSourceType: 0,
    brandName: null,
    incomplete: 0,
    fillOrCheck: 0,
    isSp: 0,
    spId: null,
    upcCode: "",
    description: "",
    attrList: [],
    wmProductSpuExtends: null,
    unreleasedId: 0,
    suggestCategoryId: 0,
    isStopSell: 0,
    isPlatformStopSell: 0,
    unComplianceFlag: 0,
    originName: null,
    nameClone: null,
    flavour: null,
    tagCount: 1,
    smartSort: null,
    pictures: [
      "http://p1.meituan.net/shangouproductapi/b783a8f3a5cab13f6f98747ee01eb574347031.jpg",
      "http://p0.meituan.net/shangouproductapi/a448043ccc3d738576554ab86861c115506237.jpg",
      "http://p0.meituan.net/shangouproductapi/7c8c320df3e0d80ac22dcd8f06889e9d315783.jpg",
      "http://p0.meituan.net/shangouproductapi/2dd1f96787609be19899205d88a927b4426459.jpg",
      "http://p0.meituan.net/shangouproductapi/9610c8ac40906ee38ea851d26bb4bea9423972.jpg",
      "http://p0.meituan.net/shangouproductapi/465c97c6bce7066e519b9de5dcc371db421047.jpg",
      "http://p0.meituan.net/shangouproductapi/63963232db1fb2e5f2f12f6ebd0b716f439761.jpg",
      "http://p0.meituan.net/shangouproductapi/e5c119802d450e656e2d4bb6049be156558488.jpg",
      "http://p0.meituan.net/shangouproductapi/235bcc34a38f9780aa2f27790861b806457205.jpg",
      "http://p0.meituan.net/shangouproductapi/f86fa8e936ec0e7cf612eecd0f731399324977.jpg",
    ],
    approvalNumberPics: null,
    isSupportApprovalNumberPic: 0,
    labels: null,
    wmProductVideo: null,
    platformLimitSaleRule: null,
    tagList: [
      {
        id: 1194074432,
        wm_poi_id: 0,
        poi_id: 0,
        name: "拖鞋凉鞋",
        sequence: 0,
        ctime: 0,
        utime: 0,
        valid: 1,
        description: "",
        act_policy_id: 0,
        wm_category_code: "",
        node_path: "",
        level: 2,
        parent_id: 1194063567,
        buz_type: 0,
        app_tag_code: "",
        top_flag: 0,
        time_zone: "",
        tag_type: 0,
        is_leaf: 1,
        outer_ftag_id: -1,
        extend: '{"sortType":0,"status":0,"topCount":0}',
        children: null,
        tempTagId: 0,
        hqTagId: 0,
        hqId: 0,
        is_top: 0,
        tagrelSequence: 0,
        marketplaceId: null,
        overrideConfig: 0,
        cStatus: 0,
        templateId: 0,
        markIds: null,
        setDescription: true,
        setExtend: true,
        setHqId: false,
        setMarketplaceId: false,
        setOverrideConfig: false,
        setPoi_id: false,
        setTag_type: false,
        setSequence: false,
        setValid: false,
        setCtime: false,
        setUtime: false,
        setId: true,
        setName: true,
        setLevel: true,
        setWm_category_code: true,
        setWm_poi_id: false,
        setIs_top: false,
        setTemplateId: false,
        setAct_policy_id: false,
        setNode_path: true,
        setParent_id: true,
        setBuz_type: false,
        setApp_tag_code: true,
        setTop_flag: true,
        setTime_zone: true,
        setIs_leaf: true,
        setOuter_ftag_id: false,
        childrenSize: 0,
        childrenIterator: null,
        setChildren: false,
        setTempTagId: false,
        setHqTagId: false,
        setTagrelSequence: true,
        cstatus: 0,
        setCStatus: false,
        markIdsSize: 0,
        markIdsIterator: null,
        setMarkIds: false,
      },
    ],
    categoryNamePath: "服饰鞋包,男鞋,男士凉鞋",
    categoryIdPath: ",200001071,200001074,200001085,",
    auditStatus: 2,
    complianceStatus: 2,
    compositeAuditStatus: 2,
    categoryType: 0,
    missingRequiredInfo: false,
    auditCreateTime: 0,
    auditUpdateTime: 0,
    saveOrUpdate: 0,
    auditUpdateData: false,
    sgLabels: null,
    combinationLabel: 2,
    skuId: 0,
    saleType: 1,
    shippingTime: '{"code":1,"value":"-"}',
    gracePeriodEndTime: 0,
    approachSoldOut: false,
    recommandAvailableTime: null,
    violationId: null,
    platformStopSellLabelMsg: null,
    platformStopSellTips: null,
    cspuId: 0,
    cspuIdMergedSpuCount: 0,
    cpvGuidePicList: [],
    cpvGuidePicConfigList: [
      {
        imgTitle: "吊牌及洗唛",
        imgDesc:
          "建议优先上线吊牌及洗唛，同时支持单商品上传多张图片，信息在不同图片时需包含【执行标准号】、【安全类别】、【面料成分含量】、【面料成分】，图片中的有效文本内容要清晰、可识别，无模糊、反光、过曝和有水印等问题。图片和文字需正向，背景无杂乱，裁切、遮挡、折叠、阴影等。",
        imgType: 7,
        urlList: [
          "https://p0.meituan.net/sgspyy/a8ad3b6fb91180134ae4182cf94a13be15105.jpg",
          "https://p0.meituan.net/sgspyy/ae4e35870daa0b98ac9aa5663b2f725018045.jpg",
          "https://p0.meituan.net/sgspyy/dc47af058e3bc81ccd43aacb201de4a723290.jpg",
          "https://p1.meituan.net/sgspyy/6587afcb6d910cbc130eed31bcda270f38717.jpg",
        ],
        picNumLimit: 4,
        picRequired: false,
        picPriority: 3,
        customerDisplayUrl:
          "https://p1.meituan.net/sgspyy/944f6e6f5e27fa47d1ed3d6a1bb55d6057708.jpg",
        cDisplay: 1,
      },
    ],
    appSpuCode: "mtcode_2041438056921456725",
    enableStockEditing: true,
    combineSubSpu: false,
    noStockAutoClear: false,
    limitRuleId: 0,
  },
  {
    id: 25264913299,
    name: "可爱米奇超厚底洞洞鞋女夏季增高防滑凉鞋外穿沙滩EVA包头拖鞋6cm（XZ71）",
    sellCount: 0,
    likeCount: 0,
    sellStatus: 0,
    picture:
      "http://p0.meituan.net/shangouproductapi/8a15fd1fd252f499dad0e36c1cda305b234589.jpg@88h_88w_1e",
    tagId: 1194092162,
    tagName: "休闲拖鞋凉鞋",
    wmProductSkus: [
      {
        id: 47183797242,
        spec: "黑色+35-36 ",
        price: 76,
        discountPrice: -1,
        stock: 999,
        boxPrice: 0,
        boxNum: 1,
        upcCode: "",
        sourceFoodCode: "",
        weight: 99,
        weight_unit: "克(g)",
        minOrderCount: 1,
        weight4g: 0,
        sellStatus: 0,
      },
      {
        id: 47183797243,
        spec: "黑色+37-38 ",
        price: 76,
        discountPrice: -1,
        stock: 0,
        boxPrice: 0,
        boxNum: 1,
        upcCode: "",
        sourceFoodCode: "",
        weight: 99,
        weight_unit: "克(g)",
        minOrderCount: 1,
        weight4g: 0,
        sellStatus: 0,
      },
      {
        id: 47183797244,
        spec: "黑色+39-40 ",
        price: 76,
        discountPrice: -1,
        stock: 999,
        boxPrice: 0,
        boxNum: 1,
        upcCode: "",
        sourceFoodCode: "",
        weight: 99,
        weight_unit: "克(g)",
        minOrderCount: 1,
        weight4g: 0,
        sellStatus: 0,
      },
    ],
    categoryId: 200001092,
    categoryName: "女士凉鞋",
    brandId: 0,
    spBrandId: 0,
    brandSourceType: 0,
    brandName: null,
    incomplete: 0,
    fillOrCheck: 0,
    isSp: 0,
    spId: null,
    upcCode: "",
    description: "",
    attrList: [],
    wmProductSpuExtends: null,
    unreleasedId: 0,
    suggestCategoryId: 0,
    isStopSell: 0,
    isPlatformStopSell: 0,
    unComplianceFlag: 0,
    originName: null,
    nameClone: null,
    flavour: null,
    tagCount: 1,
    smartSort: null,
    pictures: [
      "http://p0.meituan.net/shangouproductapi/8a15fd1fd252f499dad0e36c1cda305b234589.jpg",
      "http://p0.meituan.net/shangouproductapi/9a4eb6716ec76557fb193f88245dfae9376956.jpg",
      "http://p1.meituan.net/shangouproductapi/39a2c9b5351a3f8ae9f10a6c03094368337427.jpg",
      "http://p0.meituan.net/shangouproductapi/ebf89160e8698100fcfa5336385adb71487445.jpg",
      "http://p1.meituan.net/shangouproductapi/0bbf55e0ae498dcb353849ca51b49615297095.jpg",
      "",
      "",
      "",
      "",
      "",
    ],
    approvalNumberPics: null,
    isSupportApprovalNumberPic: 0,
    labels: null,
    wmProductVideo: null,
    platformLimitSaleRule: null,
    tagList: [
      {
        id: 1194092162,
        wm_poi_id: 0,
        poi_id: 0,
        name: "休闲拖鞋凉鞋",
        sequence: 0,
        ctime: 0,
        utime: 0,
        valid: 1,
        description: "",
        act_policy_id: 0,
        wm_category_code: "",
        node_path: "",
        level: 2,
        parent_id: 1194057644,
        buz_type: 0,
        app_tag_code: "",
        top_flag: 0,
        time_zone: "",
        tag_type: 0,
        is_leaf: 1,
        outer_ftag_id: -1,
        extend: '{"sortType":0,"status":0,"topCount":0}',
        children: null,
        tempTagId: 0,
        hqTagId: 0,
        hqId: 0,
        is_top: 0,
        tagrelSequence: 0,
        marketplaceId: null,
        overrideConfig: 0,
        cStatus: 0,
        templateId: 0,
        markIds: null,
        setDescription: true,
        setExtend: true,
        setHqId: false,
        setMarketplaceId: false,
        setOverrideConfig: false,
        setPoi_id: false,
        setTag_type: false,
        setSequence: false,
        setValid: false,
        setCtime: false,
        setUtime: false,
        setId: true,
        setName: true,
        setLevel: true,
        setWm_category_code: true,
        setWm_poi_id: false,
        setIs_top: false,
        setTemplateId: false,
        setAct_policy_id: false,
        setNode_path: true,
        setParent_id: true,
        setBuz_type: false,
        setApp_tag_code: true,
        setTop_flag: true,
        setTime_zone: true,
        setIs_leaf: true,
        setOuter_ftag_id: false,
        childrenSize: 0,
        childrenIterator: null,
        setChildren: false,
        setTempTagId: false,
        setHqTagId: false,
        setTagrelSequence: true,
        cstatus: 0,
        setCStatus: false,
        markIdsSize: 0,
        markIdsIterator: null,
        setMarkIds: false,
      },
    ],
    categoryNamePath: "服饰鞋包,女鞋,女士凉鞋",
    categoryIdPath: ",200001071,200001075,200001092,",
    auditStatus: 2,
    complianceStatus: 2,
    compositeAuditStatus: 2,
    categoryType: 0,
    missingRequiredInfo: false,
    auditCreateTime: 0,
    auditUpdateTime: 0,
    saveOrUpdate: 0,
    auditUpdateData: false,
    sgLabels: null,
    combinationLabel: 2,
    skuId: 0,
    saleType: 1,
    shippingTime: '{"code":1,"value":"-"}',
    gracePeriodEndTime: 0,
    approachSoldOut: false,
    recommandAvailableTime: null,
    violationId: null,
    platformStopSellLabelMsg: null,
    platformStopSellTips: null,
    cspuId: 0,
    cspuIdMergedSpuCount: 0,
    cpvGuidePicList: [],
    cpvGuidePicConfigList: [
      {
        imgTitle: "吊牌及洗唛",
        imgDesc:
          "建议优先上线吊牌及洗唛，同时支持单商品上传多张图片，信息在不同图片时需包含【执行标准号】、【安全类别】、【面料成分含量】、【面料成分】，图片中的有效文本内容要清晰、可识别，无模糊、反光、过曝和有水印等问题。图片和文字需正向，背景无杂乱，裁切、遮挡、折叠、阴影等。",
        imgType: 7,
        urlList: [
          "https://p0.meituan.net/sgspyy/a8ad3b6fb91180134ae4182cf94a13be15105.jpg",
          "https://p0.meituan.net/sgspyy/ae4e35870daa0b98ac9aa5663b2f725018045.jpg",
          "https://p0.meituan.net/sgspyy/dc47af058e3bc81ccd43aacb201de4a723290.jpg",
          "https://p1.meituan.net/sgspyy/6587afcb6d910cbc130eed31bcda270f38717.jpg",
        ],
        picNumLimit: 4,
        picRequired: false,
        picPriority: 3,
        customerDisplayUrl:
          "https://p1.meituan.net/sgspyy/944f6e6f5e27fa47d1ed3d6a1bb55d6057708.jpg",
        cDisplay: 1,
      },
    ],
    appSpuCode: "mtcode_2041437369219588158",
    enableStockEditing: true,
    combineSubSpu: false,
    noStockAutoClear: false,
    limitRuleId: 0,
  },
  {
    id: 25266379389,
    name: "儿童洞洞鞋疯狂动物防滑朱迪男童女童两穿卡通宝宝软底尼克拖鞋XZ72",
    sellCount: 0,
    likeCount: 0,
    sellStatus: 0,
    picture:
      "http://p0.meituan.net/shangouproductapi/b51639fda1debb9567c80049aa77cf3d474272.jpg@88h_88w_1e",
    tagId: 1495363490,
    tagName: "儿童鞋类",
    wmProductSkus: [
      {
        id: 47015771114,
        spec: "粉色系+24-25",
        price: 69,
        discountPrice: -1,
        stock: 999,
        boxPrice: 0,
        boxNum: 1,
        upcCode: "",
        sourceFoodCode: "",
        weight: 99,
        weight_unit: "克(g)",
        minOrderCount: 1,
        weight4g: 0,
        sellStatus: 0,
      },
      {
        id: 47015771115,
        spec: "粉色系+26-27",
        price: 69,
        discountPrice: -1,
        stock: 999,
        boxPrice: 0,
        boxNum: 1,
        upcCode: "",
        sourceFoodCode: "",
        weight: 99,
        weight_unit: "克(g)",
        minOrderCount: 1,
        weight4g: 0,
        sellStatus: 0,
      },
      {
        id: 47015771116,
        spec: "粉色系+28-29",
        price: 69,
        discountPrice: -1,
        stock: 0,
        boxPrice: 0,
        boxNum: 1,
        upcCode: "",
        sourceFoodCode: "",
        weight: 99,
        weight_unit: "克(g)",
        minOrderCount: 1,
        weight4g: 0,
        sellStatus: 0,
      },
      {
        id: 47015771117,
        spec: "粉色系+30-31",
        price: 69,
        discountPrice: -1,
        stock: 999,
        boxPrice: 0,
        boxNum: 1,
        upcCode: "",
        sourceFoodCode: "",
        weight: 99,
        weight_unit: "克(g)",
        minOrderCount: 1,
        weight4g: 0,
        sellStatus: 0,
      },
      {
        id: 47015771118,
        spec: "粉色系+32-33",
        price: 69,
        discountPrice: -1,
        stock: 999,
        boxPrice: 0,
        boxNum: 1,
        upcCode: "",
        sourceFoodCode: "",
        weight: 99,
        weight_unit: "克(g)",
        minOrderCount: 1,
        weight4g: 0,
        sellStatus: 0,
      },
      {
        id: 47015771119,
        spec: "粉色系+34-35",
        price: 69,
        discountPrice: -1,
        stock: 999,
        boxPrice: 0,
        boxNum: 1,
        upcCode: "",
        sourceFoodCode: "",
        weight: 99,
        weight_unit: "克(g)",
        minOrderCount: 1,
        weight4g: 0,
        sellStatus: 0,
      },
      {
        id: 47015771120,
        spec: "蓝色系+24-25",
        price: 69,
        discountPrice: -1,
        stock: 999,
        boxPrice: 0,
        boxNum: 1,
        upcCode: "",
        sourceFoodCode: "",
        weight: 99,
        weight_unit: "克(g)",
        minOrderCount: 1,
        weight4g: 0,
        sellStatus: 0,
      },
      {
        id: 47015771121,
        spec: "蓝色系+26-27",
        price: 69,
        discountPrice: -1,
        stock: 999,
        boxPrice: 0,
        boxNum: 1,
        upcCode: "",
        sourceFoodCode: "",
        weight: 99,
        weight_unit: "克(g)",
        minOrderCount: 1,
        weight4g: 0,
        sellStatus: 0,
      },
      {
        id: 47015771122,
        spec: "蓝色系+28-29",
        price: 69,
        discountPrice: -1,
        stock: 999,
        boxPrice: 0,
        boxNum: 1,
        upcCode: "",
        sourceFoodCode: "",
        weight: 99,
        weight_unit: "克(g)",
        minOrderCount: 1,
        weight4g: 0,
        sellStatus: 0,
      },
      {
        id: 47015771123,
        spec: "蓝色系+30-31",
        price: 69,
        discountPrice: -1,
        stock: 999,
        boxPrice: 0,
        boxNum: 1,
        upcCode: "",
        sourceFoodCode: "",
        weight: 99,
        weight_unit: "克(g)",
        minOrderCount: 1,
        weight4g: 0,
        sellStatus: 0,
      },
      {
        id: 47015771124,
        spec: "蓝色系+32-33",
        price: 69,
        discountPrice: -1,
        stock: 999,
        boxPrice: 0,
        boxNum: 1,
        upcCode: "",
        sourceFoodCode: "",
        weight: 99,
        weight_unit: "克(g)",
        minOrderCount: 1,
        weight4g: 0,
        sellStatus: 0,
      },
      {
        id: 47015771125,
        spec: "蓝色系+34-35",
        price: 69,
        discountPrice: -1,
        stock: 999,
        boxPrice: 0,
        boxNum: 1,
        upcCode: "",
        sourceFoodCode: "",
        weight: 99,
        weight_unit: "克(g)",
        minOrderCount: 1,
        weight4g: 0,
        sellStatus: 0,
      },
    ],
    categoryId: 200004087,
    categoryName: "儿童凉鞋",
    brandId: 0,
    spBrandId: 0,
    brandSourceType: 0,
    brandName: null,
    incomplete: 0,
    fillOrCheck: 0,
    isSp: 0,
    spId: null,
    upcCode: "",
    description: "",
    attrList: [],
    wmProductSpuExtends: null,
    unreleasedId: 0,
    suggestCategoryId: 0,
    isStopSell: 0,
    isPlatformStopSell: 0,
    unComplianceFlag: 0,
    originName: null,
    nameClone: null,
    flavour: null,
    tagCount: 1,
    smartSort: null,
    pictures: [
      "http://p0.meituan.net/shangouproductapi/b51639fda1debb9567c80049aa77cf3d474272.jpg",
      "http://p1.meituan.net/shangouproductapi/34e92bab7c9a03102340246ea267077d454050.jpg",
      "http://p0.meituan.net/shangouproductapi/9146dc982223e7f6f561d2745eb891cf465454.jpg",
      "http://p0.meituan.net/shangouproductapi/97925df280de9d224b7d57bc6e4c3c5a594084.jpg",
      "http://p0.meituan.net/shangouproductapi/43d860f9abf203fbd8581518d3c0254a433218.jpg",
      "http://p0.meituan.net/shangouproductapi/7594ccffae693308757e4227cd613329451046.jpg",
      "http://p0.meituan.net/shangouproductapi/d24a38feb7ffcb3852a21b2cd19a9c88564851.jpg",
      "http://p0.meituan.net/shangouproductapi/75c384af91b09089b128e8402c0c14d6398770.jpg",
      "http://p0.meituan.net/shangouproductapi/cea862030cb2832a15bb586232b15ee9469261.jpg",
      "http://p0.meituan.net/shangouproductapi/14724e2bbd648ea24d29dd6098e26445576053.jpg",
    ],
    approvalNumberPics: null,
    isSupportApprovalNumberPic: 0,
    labels: null,
    wmProductVideo: null,
    platformLimitSaleRule: null,
    tagList: [
      {
        id: 1495363490,
        wm_poi_id: 0,
        poi_id: 0,
        name: "儿童鞋类",
        sequence: 0,
        ctime: 0,
        utime: 0,
        valid: 1,
        description: "",
        act_policy_id: 0,
        wm_category_code: "",
        node_path: "",
        level: 1,
        parent_id: 0,
        buz_type: 0,
        app_tag_code: "",
        top_flag: 0,
        time_zone: "",
        tag_type: 0,
        is_leaf: 1,
        outer_ftag_id: -1,
        extend: '{"sortType":0,"status":0,"topCount":0}',
        children: null,
        tempTagId: 0,
        hqTagId: 0,
        hqId: 0,
        is_top: 0,
        tagrelSequence: 0,
        marketplaceId: null,
        overrideConfig: 0,
        cStatus: 0,
        templateId: 0,
        markIds: null,
        setDescription: true,
        setExtend: true,
        setHqId: false,
        setMarketplaceId: false,
        setOverrideConfig: false,
        setPoi_id: false,
        setTag_type: false,
        setSequence: false,
        setValid: false,
        setCtime: false,
        setUtime: false,
        setId: true,
        setName: true,
        setLevel: true,
        setWm_category_code: true,
        setWm_poi_id: false,
        setIs_top: false,
        setTemplateId: false,
        setAct_policy_id: false,
        setNode_path: true,
        setParent_id: true,
        setBuz_type: false,
        setApp_tag_code: true,
        setTop_flag: true,
        setTime_zone: true,
        setIs_leaf: true,
        setOuter_ftag_id: false,
        childrenSize: 0,
        childrenIterator: null,
        setChildren: false,
        setTempTagId: false,
        setHqTagId: false,
        setTagrelSequence: true,
        cstatus: 0,
        setCStatus: false,
        markIdsSize: 0,
        markIdsIterator: null,
        setMarkIds: false,
      },
    ],
    categoryNamePath: "母婴用品,童装童鞋,儿童凉鞋",
    categoryIdPath: ",200001687,200004070,200004087,",
    auditStatus: 2,
    complianceStatus: 2,
    compositeAuditStatus: 2,
    categoryType: 0,
    missingRequiredInfo: false,
    auditCreateTime: 0,
    auditUpdateTime: 0,
    saveOrUpdate: 0,
    auditUpdateData: false,
    sgLabels: null,
    combinationLabel: 2,
    skuId: 0,
    saleType: 1,
    shippingTime: '{"code":1,"value":"-"}',
    gracePeriodEndTime: 0,
    approachSoldOut: false,
    recommandAvailableTime: null,
    violationId: null,
    platformStopSellLabelMsg: null,
    platformStopSellTips: null,
    cspuId: 0,
    cspuIdMergedSpuCount: 0,
    cpvGuidePicList: [],
    cpvGuidePicConfigList: [
      {
        imgTitle: "吊牌及洗唛",
        imgDesc:
          "建议优先上线吊牌及洗唛，同时支持单商品上传多张图片，信息在不同图片时需包含【执行标准号】、【面料成分含量】、【面料成分】，图片中的有效文本内容要清晰、可识别，无模糊、反光、过曝和有水印等问题。图片和文字需正向，背景无杂乱，裁切、遮挡、折叠、阴影等。",
        imgType: 7,
        urlList: [
          "https://p0.meituan.net/sgspyy/a8ad3b6fb91180134ae4182cf94a13be15105.jpg",
          "https://p0.meituan.net/sgspyy/ae4e35870daa0b98ac9aa5663b2f725018045.jpg",
          "https://p0.meituan.net/sgspyy/dc47af058e3bc81ccd43aacb201de4a723290.jpg",
          "https://p1.meituan.net/sgspyy/6587afcb6d910cbc130eed31bcda270f38717.jpg",
        ],
        picNumLimit: 4,
        picRequired: false,
        picPriority: 3,
        customerDisplayUrl:
          "https://p1.meituan.net/sgspyy/944f6e6f5e27fa47d1ed3d6a1bb55d6057708.jpg",
        cDisplay: 1,
      },
    ],
    appSpuCode: "mtcode_2041436006137962594",
    enableStockEditing: true,
    combineSubSpu: false,
    noStockAutoClear: false,
    limitRuleId: 0,
  },
  {
    id: 25213452280,
    name: "男士商务正装职业工作皮鞋男韩版休闲黑色低帮鞋平底透气XZ70",
    sellCount: 0,
    likeCount: 0,
    sellStatus: 0,
    picture:
      "http://p0.meituan.net/shangouproductapi/f4087b2926193641396bfb55004a1f6947665.jpg@88h_88w_1e",
    tagId: 1194052712,
    tagName: "皮鞋",
    wmProductSkus: [
      {
        id: 46918580522,
        spec: "",
        price: 69,
        discountPrice: -1,
        stock: 999,
        boxPrice: 0,
        boxNum: 1,
        upcCode: "",
        sourceFoodCode: "",
        weight: 200,
        weight_unit: "克(g)",
        minOrderCount: 1,
        weight4g: 0,
        sellStatus: 0,
      },
    ],
    categoryId: 200001082,
    categoryName: "男士皮鞋",
    brandId: 0,
    spBrandId: 0,
    brandSourceType: 0,
    brandName: null,
    incomplete: 0,
    fillOrCheck: 0,
    isSp: 0,
    spId: null,
    upcCode: "",
    description: "",
    attrList: [],
    wmProductSpuExtends: null,
    unreleasedId: 0,
    suggestCategoryId: 0,
    isStopSell: 0,
    isPlatformStopSell: 0,
    unComplianceFlag: 0,
    originName: null,
    nameClone: null,
    flavour: null,
    tagCount: 1,
    smartSort: null,
    pictures: [
      "http://p0.meituan.net/shangouproductapi/f4087b2926193641396bfb55004a1f6947665.jpg",
      "http://p1.meituan.net/shangouproductapi/65ee7a2bf72e2a3850d89e5639d8a50883154.jpg",
      "http://p0.meituan.net/shangouproductapi/6e6f4db58b05cb4cefcded7f487a3f6d110759.jpg",
      "http://p0.meituan.net/shangouproductapi/23859e21474db6c322e92bd82948e770102423.jpg",
      "http://p0.meituan.net/shangouproductapi/284ec834807da8b0c041c7afdd4c912376247.jpg",
      "",
      "",
      "",
      "",
      "",
    ],
    approvalNumberPics: null,
    isSupportApprovalNumberPic: 0,
    labels: null,
    wmProductVideo: null,
    platformLimitSaleRule: null,
    tagList: [
      {
        id: 1194052712,
        wm_poi_id: 0,
        poi_id: 0,
        name: "皮鞋",
        sequence: 0,
        ctime: 0,
        utime: 0,
        valid: 1,
        description: "",
        act_policy_id: 0,
        wm_category_code: "",
        node_path: "",
        level: 2,
        parent_id: 1194063567,
        buz_type: 0,
        app_tag_code: "",
        top_flag: 0,
        time_zone: "",
        tag_type: 0,
        is_leaf: 1,
        outer_ftag_id: -1,
        extend: '{"sortType":0,"status":0,"topCount":0}',
        children: null,
        tempTagId: 0,
        hqTagId: 0,
        hqId: 0,
        is_top: 0,
        tagrelSequence: 0,
        marketplaceId: null,
        overrideConfig: 0,
        cStatus: 0,
        templateId: 0,
        markIds: null,
        setDescription: true,
        setExtend: true,
        setHqId: false,
        setMarketplaceId: false,
        setOverrideConfig: false,
        setPoi_id: false,
        setTag_type: false,
        setSequence: false,
        setValid: false,
        setCtime: false,
        setUtime: false,
        setId: true,
        setName: true,
        setLevel: true,
        setWm_category_code: true,
        setWm_poi_id: false,
        setIs_top: false,
        setTemplateId: false,
        setAct_policy_id: false,
        setNode_path: true,
        setParent_id: true,
        setBuz_type: false,
        setApp_tag_code: true,
        setTop_flag: true,
        setTime_zone: true,
        setIs_leaf: true,
        setOuter_ftag_id: false,
        childrenSize: 0,
        childrenIterator: null,
        setChildren: false,
        setTempTagId: false,
        setHqTagId: false,
        setTagrelSequence: true,
        cstatus: 0,
        setCStatus: false,
        markIdsSize: 0,
        markIdsIterator: null,
        setMarkIds: false,
      },
    ],
    categoryNamePath: "服饰鞋包,男鞋,男士皮鞋",
    categoryIdPath: ",200001071,200001074,200001082,",
    auditStatus: 2,
    complianceStatus: 2,
    compositeAuditStatus: 2,
    categoryType: 0,
    missingRequiredInfo: false,
    auditCreateTime: 0,
    auditUpdateTime: 0,
    saveOrUpdate: 0,
    auditUpdateData: false,
    sgLabels: null,
    combinationLabel: 2,
    skuId: 0,
    saleType: 1,
    shippingTime: '{"code":1,"value":"-"}',
    gracePeriodEndTime: 0,
    approachSoldOut: false,
    recommandAvailableTime: null,
    violationId: null,
    platformStopSellLabelMsg: null,
    platformStopSellTips: null,
    cspuId: 0,
    cspuIdMergedSpuCount: 0,
    cpvGuidePicList: [],
    cpvGuidePicConfigList: [
      {
        imgTitle: "吊牌及洗唛",
        imgDesc:
          "建议优先上线吊牌及洗唛，同时支持单商品上传多张图片，信息在不同图片时需包含【执行标准号】、【安全类别】、【面料成分含量】、【面料成分】，图片中的有效文本内容要清晰、可识别，无模糊、反光、过曝和有水印等问题。图片和文字需正向，背景无杂乱，裁切、遮挡、折叠、阴影等。",
        imgType: 7,
        urlList: [
          "https://p0.meituan.net/sgspyy/a8ad3b6fb91180134ae4182cf94a13be15105.jpg",
          "https://p0.meituan.net/sgspyy/ae4e35870daa0b98ac9aa5663b2f725018045.jpg",
          "https://p0.meituan.net/sgspyy/dc47af058e3bc81ccd43aacb201de4a723290.jpg",
          "https://p1.meituan.net/sgspyy/6587afcb6d910cbc130eed31bcda270f38717.jpg",
        ],
        picNumLimit: 4,
        picRequired: false,
        picPriority: 3,
        customerDisplayUrl:
          "https://p1.meituan.net/sgspyy/944f6e6f5e27fa47d1ed3d6a1bb55d6057708.jpg",
        cDisplay: 1,
      },
    ],
    appSpuCode: "mtcode_2039919089354711088",
    enableStockEditing: true,
    combineSubSpu: false,
    noStockAutoClear: false,
    limitRuleId: 0,
  },
  {
    id: 24634579729,
    name: "唐韵轻衫铺新款汉服女【花朝】唐制复原一片式齐胸襦裙春夏款【上衣+裙子+披帛+肩带】A448",
    sellCount: 0,
    likeCount: 0,
    sellStatus: 0,
    picture:
      "http://p0.meituan.net/shangouproductapi/e71b715869ab181e4006457e2ec8236d256225.jpg@88h_88w_1e",
    tagId: 1495671023,
    tagName: "汉服",
    wmProductSkus: [
      {
        id: 45605133999,
        spec: "",
        price: 159,
        discountPrice: -1,
        stock: 999,
        boxPrice: 0,
        boxNum: 1,
        upcCode: "",
        sourceFoodCode: "",
        weight: 200,
        weight_unit: "克(g)",
        minOrderCount: 1,
        weight4g: 0,
        sellStatus: 0,
      },
    ],
    categoryId: 200001185,
    categoryName: "唐装/民族服装",
    brandId: 0,
    spBrandId: 0,
    brandSourceType: 0,
    brandName: null,
    incomplete: 0,
    fillOrCheck: 0,
    isSp: 0,
    spId: null,
    upcCode: "",
    description: "",
    attrList: [],
    wmProductSpuExtends: null,
    unreleasedId: 0,
    suggestCategoryId: 0,
    isStopSell: 0,
    isPlatformStopSell: 0,
    unComplianceFlag: 0,
    originName: null,
    nameClone: null,
    flavour: null,
    tagCount: 1,
    smartSort: null,
    pictures: [
      "http://p0.meituan.net/shangouproductapi/e71b715869ab181e4006457e2ec8236d256225.jpg",
      "http://p1.meituan.net/shangouproductapi/e0e0230ac27907d8b87b9c2937a36010172770.jpg",
      "http://p0.meituan.net/shangouproductapi/d4a88fd109f0a1f42b5facda89241cdf74658.jpg",
      "http://p0.meituan.net/shangouproductapi/51ca32bcf93ade2340a04f1242710bdb76718.jpg",
      "http://p0.meituan.net/shangouproductapi/9e5ac7fcbe6577451de8d827837148e1320235.jpg",
      "",
      "",
      "",
      "",
      "",
    ],
    approvalNumberPics: null,
    isSupportApprovalNumberPic: 0,
    labels: null,
    wmProductVideo: null,
    platformLimitSaleRule: null,
    tagList: [
      {
        id: 1495671023,
        wm_poi_id: 0,
        poi_id: 0,
        name: "汉服",
        sequence: 0,
        ctime: 0,
        utime: 0,
        valid: 1,
        description: "",
        act_policy_id: 0,
        wm_category_code: "",
        node_path: "",
        level: 2,
        parent_id: 1500073516,
        buz_type: 0,
        app_tag_code: "",
        top_flag: 0,
        time_zone: "",
        tag_type: 0,
        is_leaf: 1,
        outer_ftag_id: -1,
        extend: '{"sortType":0,"status":0,"topCount":0}',
        children: null,
        tempTagId: 0,
        hqTagId: 0,
        hqId: 0,
        is_top: 0,
        tagrelSequence: 30,
        marketplaceId: null,
        overrideConfig: 0,
        cStatus: 0,
        templateId: 0,
        markIds: null,
        setDescription: true,
        setExtend: true,
        setHqId: false,
        setMarketplaceId: false,
        setOverrideConfig: false,
        setPoi_id: false,
        setTag_type: false,
        setSequence: false,
        setValid: false,
        setCtime: false,
        setUtime: false,
        setId: true,
        setName: true,
        setLevel: true,
        setWm_category_code: true,
        setWm_poi_id: false,
        setIs_top: false,
        setTemplateId: false,
        setAct_policy_id: false,
        setNode_path: true,
        setParent_id: true,
        setBuz_type: false,
        setApp_tag_code: true,
        setTop_flag: true,
        setTime_zone: true,
        setIs_leaf: true,
        setOuter_ftag_id: false,
        childrenSize: 0,
        childrenIterator: null,
        setChildren: false,
        setTempTagId: false,
        setHqTagId: false,
        setTagrelSequence: true,
        cstatus: 0,
        setCStatus: false,
        markIdsSize: 0,
        markIdsIterator: null,
        setMarkIds: false,
      },
    ],
    categoryNamePath: "服饰鞋包,女装,唐装/民族服装",
    categoryIdPath: ",200001071,200001081,200001185,",
    auditStatus: 2,
    complianceStatus: 2,
    compositeAuditStatus: 2,
    categoryType: 0,
    missingRequiredInfo: false,
    auditCreateTime: 0,
    auditUpdateTime: 0,
    saveOrUpdate: 0,
    auditUpdateData: false,
    sgLabels: null,
    combinationLabel: 2,
    skuId: 0,
    saleType: 1,
    shippingTime: '{"code":1,"value":"-"}',
    gracePeriodEndTime: 0,
    approachSoldOut: false,
    recommandAvailableTime: null,
    violationId: null,
    platformStopSellLabelMsg: null,
    platformStopSellTips: null,
    cspuId: 0,
    cspuIdMergedSpuCount: 0,
    cpvGuidePicList: [],
    cpvGuidePicConfigList: [
      {
        imgTitle: "尺码表",
        imgDesc:
          "建议优先上传尺码表图片，同时支持单商品上传多张图片，建议包含以下信息：关键身体维度及对应尺码的相关数据，如S/M/L/XL等尺码及对应的胸围、衣长、腰围、臀围等信息；内容清晰可识别，无模糊、反光、水印、图片正向无杂乱；",
        imgType: 14,
        urlList: [
          "https://p0.meituan.net/sgspyy/f9caf4222c61ea8cbf9faf2ad5ea36be212340.png",
        ],
        picNumLimit: 4,
        picRequired: false,
        picPriority: 1,
        customerDisplayUrl:
          "https://p0.meituan.net/sgspyy/9780a44d7f0985bbf74fc3d15440df1a56579.jpg",
        cDisplay: 1,
      },
      {
        imgTitle: "吊牌及洗唛",
        imgDesc:
          "建议优先上线吊牌及洗唛，同时支持单商品上传多张图片，信息在不同图片时需包含【执行标准号】、【面料成分含量】、【面料成分】，图片中的有效文本内容要清晰、可识别，无模糊、反光、过曝和有水印等问题。图片和文字需正向，背景无杂乱，裁切、遮挡、折叠、阴影等。",
        imgType: 7,
        urlList: [
          "https://p0.meituan.net/sgspyy/a8ad3b6fb91180134ae4182cf94a13be15105.jpg",
          "https://p0.meituan.net/sgspyy/ae4e35870daa0b98ac9aa5663b2f725018045.jpg",
          "https://p0.meituan.net/sgspyy/dc47af058e3bc81ccd43aacb201de4a723290.jpg",
          "https://p1.meituan.net/sgspyy/6587afcb6d910cbc130eed31bcda270f38717.jpg",
        ],
        picNumLimit: 4,
        picRequired: false,
        picPriority: 3,
        customerDisplayUrl:
          "https://p1.meituan.net/sgspyy/944f6e6f5e27fa47d1ed3d6a1bb55d6057708.jpg",
        cDisplay: 1,
      },
    ],
    appSpuCode: "mtcode_2026994512341975072",
    enableStockEditing: true,
    combineSubSpu: false,
    noStockAutoClear: false,
    limitRuleId: 0,
  },
  {
    id: 24635642351,
    name: "刘海假发女仿真发公主切刘海片古风百搭造型自然蓬松增发量假发片/对D281",
    sellCount: 0,
    likeCount: 0,
    sellStatus: 0,
    picture:
      "http://p0.meituan.net/shangouproductapi/5a08f5ea6f673c2d1538a379fc27f597121953.jpg@88h_88w_1e",
    tagId: 1194076427,
    tagName: "发夹头饰",
    wmProductSkus: [
      {
        id: 45604256550,
        spec: "黑色一对",
        price: 29.9,
        discountPrice: -1,
        stock: 998,
        boxPrice: 0,
        boxNum: 1,
        upcCode: "",
        sourceFoodCode: "",
        weight: 100,
        weight_unit: "克(g)",
        minOrderCount: 1,
        weight4g: 0,
        sellStatus: 0,
      },
    ],
    categoryId: 200005637,
    categoryName: "其他配饰",
    brandId: 0,
    spBrandId: 0,
    brandSourceType: 0,
    brandName: null,
    incomplete: 0,
    fillOrCheck: 0,
    isSp: 0,
    spId: null,
    upcCode: "",
    description: "",
    attrList: [],
    wmProductSpuExtends: null,
    unreleasedId: 0,
    suggestCategoryId: 0,
    isStopSell: 0,
    isPlatformStopSell: 0,
    unComplianceFlag: 0,
    originName: null,
    nameClone: null,
    flavour: null,
    tagCount: 3,
    smartSort: null,
    pictures: [
      "http://p0.meituan.net/shangouproductapi/5a08f5ea6f673c2d1538a379fc27f597121953.jpg",
      "http://p0.meituan.net/shangouproductapi/e19688a050e9e67d39c13604eb9d8a3f306572.jpg",
      "http://p0.meituan.net/shangouproductapi/5da9797cadfc2898e4bd16c32e3f5baf276903.jpg",
      "http://p0.meituan.net/shangouproductapi/4c6f426a26ad592ff53e7e0bdf145d2f200016.jpg",
      "http://p0.meituan.net/shangouproductapi/c69c1a732e29cb1fcd4c6ddffd252e21338941.jpg",
      "",
      "",
      "",
      "",
      "",
    ],
    approvalNumberPics: null,
    isSupportApprovalNumberPic: 0,
    labels: null,
    wmProductVideo: null,
    platformLimitSaleRule: null,
    tagList: [
      {
        id: 1194076427,
        wm_poi_id: 0,
        poi_id: 0,
        name: "发夹头饰",
        sequence: 0,
        ctime: 0,
        utime: 0,
        valid: 1,
        description: "",
        act_policy_id: 0,
        wm_category_code: "",
        node_path: "",
        level: 2,
        parent_id: 1194053755,
        buz_type: 0,
        app_tag_code: "",
        top_flag: 0,
        time_zone: "",
        tag_type: 0,
        is_leaf: 1,
        outer_ftag_id: -1,
        extend: '{"sortType":0,"status":0,"topCount":0}',
        children: null,
        tempTagId: 0,
        hqTagId: 0,
        hqId: 0,
        is_top: 0,
        tagrelSequence: 0,
        marketplaceId: null,
        overrideConfig: 0,
        cStatus: 0,
        templateId: 0,
        markIds: null,
        setDescription: true,
        setExtend: true,
        setHqId: false,
        setMarketplaceId: false,
        setOverrideConfig: false,
        setPoi_id: false,
        setTag_type: false,
        setSequence: false,
        setValid: false,
        setCtime: false,
        setUtime: false,
        setId: true,
        setName: true,
        setLevel: true,
        setWm_category_code: true,
        setWm_poi_id: false,
        setIs_top: false,
        setTemplateId: false,
        setAct_policy_id: false,
        setNode_path: true,
        setParent_id: true,
        setBuz_type: false,
        setApp_tag_code: true,
        setTop_flag: true,
        setTime_zone: true,
        setIs_leaf: true,
        setOuter_ftag_id: false,
        childrenSize: 0,
        childrenIterator: null,
        setChildren: false,
        setTempTagId: false,
        setHqTagId: false,
        setTagrelSequence: true,
        cstatus: 0,
        setCStatus: false,
        markIdsSize: 0,
        markIdsIterator: null,
        setMarkIds: false,
      },
      {
        id: 1193962741,
        wm_poi_id: 0,
        poi_id: 0,
        name: "假毛",
        sequence: 0,
        ctime: 0,
        utime: 0,
        valid: 1,
        description: "",
        act_policy_id: 0,
        wm_category_code: "",
        node_path: "",
        level: 2,
        parent_id: 1227049062,
        buz_type: 0,
        app_tag_code: "",
        top_flag: 0,
        time_zone: "",
        tag_type: 0,
        is_leaf: 1,
        outer_ftag_id: -1,
        extend: '{"sortType":2,"status":0,"topCount":13}',
        children: null,
        tempTagId: 0,
        hqTagId: 0,
        hqId: 0,
        is_top: 0,
        tagrelSequence: 29,
        marketplaceId: null,
        overrideConfig: 0,
        cStatus: 0,
        templateId: 0,
        markIds: null,
        setDescription: true,
        setExtend: true,
        setHqId: false,
        setMarketplaceId: false,
        setOverrideConfig: false,
        setPoi_id: false,
        setTag_type: false,
        setSequence: false,
        setValid: false,
        setCtime: false,
        setUtime: false,
        setId: true,
        setName: true,
        setLevel: true,
        setWm_category_code: true,
        setWm_poi_id: false,
        setIs_top: false,
        setTemplateId: false,
        setAct_policy_id: false,
        setNode_path: true,
        setParent_id: true,
        setBuz_type: false,
        setApp_tag_code: true,
        setTop_flag: true,
        setTime_zone: true,
        setIs_leaf: true,
        setOuter_ftag_id: false,
        childrenSize: 0,
        childrenIterator: null,
        setChildren: false,
        setTempTagId: false,
        setHqTagId: false,
        setTagrelSequence: true,
        cstatus: 0,
        setCStatus: false,
        markIdsSize: 0,
        markIdsIterator: null,
        setMarkIds: false,
      },
      {
        id: 1500023884,
        wm_poi_id: 0,
        poi_id: 0,
        name: "配饰",
        sequence: 0,
        ctime: 0,
        utime: 0,
        valid: 1,
        description: "",
        act_policy_id: 0,
        wm_category_code: "",
        node_path: "",
        level: 2,
        parent_id: 1500073516,
        buz_type: 0,
        app_tag_code: "",
        top_flag: 0,
        time_zone: "",
        tag_type: 0,
        is_leaf: 1,
        outer_ftag_id: -1,
        extend: '{"sortType":0,"status":0,"topCount":0}',
        children: null,
        tempTagId: 0,
        hqTagId: 0,
        hqId: 0,
        is_top: 0,
        tagrelSequence: 2,
        marketplaceId: null,
        overrideConfig: 0,
        cStatus: 0,
        templateId: 0,
        markIds: null,
        setDescription: true,
        setExtend: true,
        setHqId: false,
        setMarketplaceId: false,
        setOverrideConfig: false,
        setPoi_id: false,
        setTag_type: false,
        setSequence: false,
        setValid: false,
        setCtime: false,
        setUtime: false,
        setId: true,
        setName: true,
        setLevel: true,
        setWm_category_code: true,
        setWm_poi_id: false,
        setIs_top: false,
        setTemplateId: false,
        setAct_policy_id: false,
        setNode_path: true,
        setParent_id: true,
        setBuz_type: false,
        setApp_tag_code: true,
        setTop_flag: true,
        setTime_zone: true,
        setIs_leaf: true,
        setOuter_ftag_id: false,
        childrenSize: 0,
        childrenIterator: null,
        setChildren: false,
        setTempTagId: false,
        setHqTagId: false,
        setTagrelSequence: true,
        cstatus: 0,
        setCStatus: false,
        markIdsSize: 0,
        markIdsIterator: null,
        setMarkIds: false,
      },
    ],
    categoryNamePath: "服饰鞋包,服饰配饰,其他配饰",
    categoryIdPath: ",200001071,200001080,200005637,",
    auditStatus: 2,
    complianceStatus: 2,
    compositeAuditStatus: 2,
    categoryType: 0,
    missingRequiredInfo: false,
    auditCreateTime: 0,
    auditUpdateTime: 0,
    saveOrUpdate: 0,
    auditUpdateData: false,
    sgLabels: null,
    combinationLabel: 2,
    skuId: 0,
    saleType: 1,
    shippingTime: '{"code":1,"value":"-"}',
    gracePeriodEndTime: 0,
    approachSoldOut: false,
    recommandAvailableTime: null,
    violationId: null,
    platformStopSellLabelMsg: null,
    platformStopSellTips: null,
    cspuId: 0,
    cspuIdMergedSpuCount: 0,
    cpvGuidePicList: [],
    cpvGuidePicConfigList: [],
    appSpuCode: "mtcode_2026993519679528998",
    enableStockEditing: true,
    combineSubSpu: false,
    noStockAutoClear: false,
    limitRuleId: 0,
  },
  {
    id: 24634257399,
    name: "夕梦阁原创汉服【凌云神鹿】唐制圆领袍男女CP款飞鱼情侣服春秋季A447",
    sellCount: 1,
    likeCount: 0,
    sellStatus: 0,
    picture:
      "http://p0.meituan.net/shangouproductapi/93c40cb6c6ed10d6d9bcc51e64df1bbf92625.jpg@88h_88w_1e",
    tagId: 1495671023,
    tagName: "汉服",
    wmProductSkus: [
      {
        id: 45604813069,
        spec: "",
        price: 159,
        discountPrice: -1,
        stock: 999,
        boxPrice: 0,
        boxNum: 1,
        upcCode: "",
        sourceFoodCode: "",
        weight: 200,
        weight_unit: "克(g)",
        minOrderCount: 1,
        weight4g: 0,
        sellStatus: 0,
      },
    ],
    categoryId: 200001185,
    categoryName: "唐装/民族服装",
    brandId: 0,
    spBrandId: 0,
    brandSourceType: 0,
    brandName: null,
    incomplete: 0,
    fillOrCheck: 0,
    isSp: 0,
    spId: null,
    upcCode: "",
    description: "",
    attrList: [],
    wmProductSpuExtends: null,
    unreleasedId: 0,
    suggestCategoryId: 0,
    isStopSell: 0,
    isPlatformStopSell: 0,
    unComplianceFlag: 0,
    originName: null,
    nameClone: null,
    flavour: null,
    tagCount: 1,
    smartSort: null,
    pictures: [
      "http://p0.meituan.net/shangouproductapi/93c40cb6c6ed10d6d9bcc51e64df1bbf92625.jpg",
      "http://p0.meituan.net/shangouproductapi/769b4698c2d448347f2f70d39b58825e110427.jpg",
      "http://p0.meituan.net/shangouproductapi/fcc0610b47e2a318d4fd5e4ab0342d7e82173.jpg",
      "http://p0.meituan.net/shangouproductapi/47625552854da0cbad94928ed621cb2799711.jpg",
      "http://p1.meituan.net/shangouproductapi/c72a0f57749d34c47d0a459e1f0eaa7775983.jpg",
      "",
      "",
      "",
      "",
      "",
    ],
    approvalNumberPics: null,
    isSupportApprovalNumberPic: 0,
    labels: null,
    wmProductVideo: null,
    platformLimitSaleRule: null,
    tagList: [
      {
        id: 1495671023,
        wm_poi_id: 0,
        poi_id: 0,
        name: "汉服",
        sequence: 0,
        ctime: 0,
        utime: 0,
        valid: 1,
        description: "",
        act_policy_id: 0,
        wm_category_code: "",
        node_path: "",
        level: 2,
        parent_id: 1500073516,
        buz_type: 0,
        app_tag_code: "",
        top_flag: 0,
        time_zone: "",
        tag_type: 0,
        is_leaf: 1,
        outer_ftag_id: -1,
        extend: '{"sortType":0,"status":0,"topCount":0}',
        children: null,
        tempTagId: 0,
        hqTagId: 0,
        hqId: 0,
        is_top: 0,
        tagrelSequence: 30,
        marketplaceId: null,
        overrideConfig: 0,
        cStatus: 0,
        templateId: 0,
        markIds: null,
        setDescription: true,
        setExtend: true,
        setHqId: false,
        setMarketplaceId: false,
        setOverrideConfig: false,
        setPoi_id: false,
        setTag_type: false,
        setSequence: false,
        setValid: false,
        setCtime: false,
        setUtime: false,
        setId: true,
        setName: true,
        setLevel: true,
        setWm_category_code: true,
        setWm_poi_id: false,
        setIs_top: false,
        setTemplateId: false,
        setAct_policy_id: false,
        setNode_path: true,
        setParent_id: true,
        setBuz_type: false,
        setApp_tag_code: true,
        setTop_flag: true,
        setTime_zone: true,
        setIs_leaf: true,
        setOuter_ftag_id: false,
        childrenSize: 0,
        childrenIterator: null,
        setChildren: false,
        setTempTagId: false,
        setHqTagId: false,
        setTagrelSequence: true,
        cstatus: 0,
        setCStatus: false,
        markIdsSize: 0,
        markIdsIterator: null,
        setMarkIds: false,
      },
    ],
    categoryNamePath: "服饰鞋包,女装,唐装/民族服装",
    categoryIdPath: ",200001071,200001081,200001185,",
    auditStatus: 2,
    complianceStatus: 2,
    compositeAuditStatus: 2,
    categoryType: 0,
    missingRequiredInfo: false,
    auditCreateTime: 0,
    auditUpdateTime: 0,
    saveOrUpdate: 0,
    auditUpdateData: false,
    sgLabels: null,
    combinationLabel: 2,
    skuId: 0,
    saleType: 1,
    shippingTime: '{"code":1,"value":"-"}',
    gracePeriodEndTime: 0,
    approachSoldOut: false,
    recommandAvailableTime: null,
    violationId: null,
    platformStopSellLabelMsg: null,
    platformStopSellTips: null,
    cspuId: 0,
    cspuIdMergedSpuCount: 0,
    cpvGuidePicList: [],
    cpvGuidePicConfigList: [
      {
        imgTitle: "尺码表",
        imgDesc:
          "建议优先上传尺码表图片，同时支持单商品上传多张图片，建议包含以下信息：关键身体维度及对应尺码的相关数据，如S/M/L/XL等尺码及对应的胸围、衣长、腰围、臀围等信息；内容清晰可识别，无模糊、反光、水印、图片正向无杂乱；",
        imgType: 14,
        urlList: [
          "https://p0.meituan.net/sgspyy/f9caf4222c61ea8cbf9faf2ad5ea36be212340.png",
        ],
        picNumLimit: 4,
        picRequired: false,
        picPriority: 1,
        customerDisplayUrl:
          "https://p0.meituan.net/sgspyy/9780a44d7f0985bbf74fc3d15440df1a56579.jpg",
        cDisplay: 1,
      },
      {
        imgTitle: "吊牌及洗唛",
        imgDesc:
          "建议优先上线吊牌及洗唛，同时支持单商品上传多张图片，信息在不同图片时需包含【执行标准号】、【面料成分含量】、【面料成分】，图片中的有效文本内容要清晰、可识别，无模糊、反光、过曝和有水印等问题。图片和文字需正向，背景无杂乱，裁切、遮挡、折叠、阴影等。",
        imgType: 7,
        urlList: [
          "https://p0.meituan.net/sgspyy/a8ad3b6fb91180134ae4182cf94a13be15105.jpg",
          "https://p0.meituan.net/sgspyy/ae4e35870daa0b98ac9aa5663b2f725018045.jpg",
          "https://p0.meituan.net/sgspyy/dc47af058e3bc81ccd43aacb201de4a723290.jpg",
          "https://p1.meituan.net/sgspyy/6587afcb6d910cbc130eed31bcda270f38717.jpg",
        ],
        picNumLimit: 4,
        picRequired: false,
        picPriority: 3,
        customerDisplayUrl:
          "https://p1.meituan.net/sgspyy/944f6e6f5e27fa47d1ed3d6a1bb55d6057708.jpg",
        cDisplay: 1,
      },
    ],
    appSpuCode: "mtcode_2026991795800272936",
    enableStockEditing: true,
    combineSubSpu: false,
    noStockAutoClear: false,
    limitRuleId: 0,
  },
];
const newpiclist = [];
for (const pic of piclist) {
  const pic_url = Array.isArray(pic.pictures) ? pic.pictures : [];
  const newpicurl = [];
  pic_url.forEach((url, index) => {
    if (!url || !url.startsWith("http")) return;
    newpicurl.push(url);
  });
  newpiclist.push({
    id: pic.id,
    name: pic.name,
    pictures: newpicurl,
  });
}
console.log(newpiclist);
console.log(newpiclist.length);
